services:
  web:
    build: ./frontend
    depends_on: [api]
    ports:
      - "80:80"

  api:
    build: ./backend
    environment:
      DATABASE_URL: sqlite:////data/app.db
      JWT_SECRET: change-me
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
